### ISSUE TITLE
no audio and error when skipping song

### ISSUE THREAD

**Issue by mmoomocow** [CodeXScreenDevelopers/CodeX-bot#4]
**Describe the bug**
After playing a song with the bot, it fails to play and then skipping, pausing etc causes an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play a song
2. No music plays
3. Attempt to skip the song
4. There's an error

**Expected behaviour**
Audio to play and no error on skipping song

**Screenshots**
![image](https://user-images.githubusercontent.com/44288823/123744885-88e88080-d903-11eb-9c16-8ebc0f4252d6.png)

**Environment**
In a server voice channel

**Additional context**

**Comment by mmoomocow** [comment]
This is likely caused by the dispatcher being unavailable, investigating the issue

**Comment by CodexScreen** [comment]
![image](https://user-images.githubusercontent.com/44288823/123748463-5bea9c80-d908-11eb-90bd-9b3a213aa1fd.png)
The issue appears to be a result of a change in youtube API. It is being fixed [here](https://github.com/amishshah/ytdl-core-discord/issues/367) in ytdl-core-discord.
ytdl-core has just fixed it, so switch to that for a temporary fix
